### ISSUE TITLE
ROI_GUI.m requires 8 varargin, but gets only 6 in pipeline.m

### ISSUE THREAD

**Issue by pgoltstein** [flatironinstitute/CaImAn-MATLAB#75]
Hi,
When running the source extraction, the pipeline script crashes when starting the ROI_GUI. 

It provides the script with 6 arguments:
`GUIout = ROI_GUI(A,options,Cn,Coor,keep,ROIvars)`

But in the ROI_GUI.m script, it seems to require 8 input arguments in the opening function:
```
%from varargin
handles.Y = varargin{1};
handles.A = varargin{2};
handles.P = varargin{3};
handles.options = varargin{4};
handles.template = varargin{5};
handles.C = varargin{6};
handles.b = varargin{7};
handles.f = varargin{8};
```

I've tried supplying the 8 arguments as requested in ROI_GUI.m, but that does not help. Any ideas on what is going wrong? Thanks!
Pieter

**Comment by HagaiHargil** [comment]
Hi there,

I encountered the same bugs but finally managed to get `run_pipeline` to finish. The GUI runs, but I'm not sure how to operate it, and I couldn't find instructions anywhere, maybe @jkobject could help us.  Anyways, here are the changes I made, I hope I didn't forget anything:

1. `run_pipeline.m`: Change the GUI lines inside the `if` statement to the following: 
```matlab
Coor = plot_contours(A,Cn,options,1); close;
GUIout = ROI_GUI(Y,A,P,options,Cn,C,b,f);
options = GUIout{2};
```
2. `ROI_GUI.m`: Change line 216 to: `[handles.CC,jsf,im] = plot_contours(handles.A_keep,handles.template,handles.options,0,[],[],[],find(handles.keep));`
3. `ROI_GUI.m`: Change line 234 to: `OUT = {handles.A_keep; handles.options; handles.ROIvars;handles.YrA;handles.CC;handles.b; handles.f;handles.S };` 
4. Add to the end of `plot_contours.m` the following lines:
```matlab
if ~exist('jsf')
    jsf = [];
end
```

Again, I'm not sure that *everything* will work, but I did manage to discard some of the ROIs using the GUI. I'll give further updates if I have anything once I run it on larger datasets.

**Comment by jkobject** [comment]
Hi there, So as I said earlier I think that my push request has not been merged fully, 
Here is what I have on my side 
```
clear;
%% load file
addpath(genpath('../ca_source_extraction'));  
nam = 'demoSue2x.tif';         
Y = bigread2(nam);
Y = Y - min(Y(:)); 
if ~isa(Y,'double');    Y = double(Y);  end         % convert to single
[d1,d2,T] = size(Y);                                % dimensions of dataset
d = d1*d2;                                          % total number of pixels

%% Set parameters
% All the parameters can be changed here look at the CNMFsetparams.m file 
% for more information about each parameters.
K = 130;                                           % number of components to be found
tau = 4;                                          % std of gaussian kernel (size of neuron) 
p = 2;                                            % order of autoregressive system (p = 0 no dynamics, p=1 just decay, p = 2, both rise and decay)
merge_thr = 0.8;                                  % merging threshold
options = CNMFSetParms(...                      
    'd1',d1,'d2',d2,...                         % dimensions of datasets
    'search_method','dilate','dist',3,...       % search locations when updating spatial components
    'deconv_method','constrained_foopsi',...    % activity deconvolution method
    'temporal_iter',2,...                       % number of block-coordinate descent steps 
    'fudge_factor',0.98,...                     % bias correction for AR coefficients
    'merge_thr',merge_thr,...                    % merging threshold
    'gSig',tau...
    );
%% Data pre-processing

[P,Y] = preprocess_data(Y,p);
[A,C,b,f,~] = initialize_components(Y,K,tau,options,P);  % initialize
Cn =  correlation_image(Y);
%% GUI ------
%this will create a User interface for the rest of the pipeline described in demoscript and 
%demo pipeline. LOOK at demo pipeline to understand how to use this GUI and what to pass it
%           
%It is a mix of everyhting found in those pipelines. In the future it will be also called by 
%the initialization GUI 
%
%run GUI will let you, refine the components manually, change the parameters and see the results,
%analyse the trace of each components, use a classification algorithm to
%find the components instead, add and remove components, save the ROIS
%and finish the pipeline with button clicks. 
%It is still an optional method.

% WARNING : do not use simplemode for now - minimum MATLAB VERSION 2014
%                   save is only compatible with the JSON matlabpackage

% here is what the GUI needs to receive in parameters
GUIout = ROI_GUI(Y,A,P,options,Cn,C,b,f);   
pause;
```

and the opening function of the GUI is this one : 
```
function ROI_GUI_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to ROI_GUI (see VARARGIN)
% Choose default command line output for ROI_GUI
handles.output = hObject;

%% INITIATE VARIABLES

%User defined values (look at the demos to knwo more about those values)
handles.sizetrain=25; %number of training data that the user needs to check
handles.MAXCELLSIZE=500; % maximum size of a component
handles.df_percentile = 30; % the percentile filtering along 
handles.window = 1000; % windiwd to compute noise
handles.min_spikes =3; % find spikes resulting in transients above min_sp x noise level


%Values for the program
handles.idx = false;
handles.selection = false;
handles.isimple =false;
handles.iscomputed =false;
handles.isdiscarded = false;
handles.isextracted = false;
handles.isdeconvolved = false;
handles.isrefined = false;
handles.saving = false;
handles.hasnew =false; 
handles.genval = 0; 
handles.shownum  =0;
handles.simplekeep = zeros(size(handles.sizetrain));


%from varargin

handles.Y = varargin{1};
handles.A = varargin{2};
handles.P = varargin{3};
handles.options = varargin{4};
handles.template = varargin{5};
handles.C = varargin{6};
handles.b = varargin{7};
handles.f = varargin{8};

Yr = reshape(handles.Y,handles.options.d1*handles.options.d2,size(handles.C,2));

[handles.A,handles.b,handles.C] = update_spatial_components(...
    Yr,handles.C,handles.f,[handles.A,handles.b],handles.P,handles.options);

handles.P.p = 0;    % set AR temporarily to zero for speed
[handles.C,handles.f,handles.P,handles.S,handles.YrA] = update_temporal_components(...
    Yr,handles.A,handles.b,handles.C,handles.f,handles.P,handles.options);


% compute center of mass
[handles.ROIvars.rval_space,handles.ROIvars.rval_time,handles.ROIvars.max_pr,...
    handles.ROIvars.sizeA,handles.keep] = classify_components(handles.Y,handles.A,handles.C,handles.b,handles.f,handles.YrA,handles.options);
handles.ROIvars.C =handles.C;
handles.ROIvars.cm = com(handles.A,handles.options.d1,handles.options.d2);
[d1,d2,handles.T] = size(handles.Y);                                % dimensions of dataset
handles.d = d1*d2;
handles.Yr = reshape(handles.Y,handles.d,handles.T);
handles.cellnum = sum(handles.keep);
handles.newneur = zeros(handles.cellnum);


% compute time variation of the components ( needed in the GUI )
traces = prctfilt(handles.ROIvars.C+handles.YrA,8,1000,100);
handles.ROIvars.fitness = compute_event_exceptionality(traces,0);
handles.ROIvars.fitness_delta = compute_event_exceptionality(diff(traces,[],2),0);

% We set everything into the GUI from the values that have sent from the User and computed before
set(handles.min_fit_delta,'String',num2str(handles.options.min_fitness_delta));
set(handles.min_fit,'String',num2str(handles.options.min_fitness));
set(handles.mincellsize,'String',num2str(handles.options.min_size_thr));
set(handles.maxcellsize,'String',num2str(handles.options.max_size_thr));
set(handles.rval_sp,'String',num2str(handles.options.space_thresh));
set(handles.rval_t,'String',num2str(handles.options.time_thresh));
set(handles.numcells,'String',num2str(handles.cellnum));
set(handles.General,'String',num2str(0));


set(handles.slider_min_fit_delta,'Value',handles.options.min_fitness_delta);
set(handles.slider_min_fit,'Value',handles.options.min_fitness);
set(handles.slider_min,'Value',handles.options.min_size_thr);
set(handles.slider_max,'Value',handles.options.max_size_thr);
set(handles.slider_rval_sp,'Value',handles.options.space_thresh);
set(handles.slider_rval_t,'Value',handles.options.time_thresh);
set(handles.SliderGeneral,'Value',0);
set(handles.unrefinedtext,'Visible','off');

%computing a first batch of kept component to display something (could have called replot instead)
handles.keep = (handles.ROIvars.rval_space > handles.options.space_thresh) &...
(handles.ROIvars.rval_time > handles.options.time_thresh) & ... 
(handles.ROIvars.sizeA >= handles.options.min_size_thr) &...
(handles.ROIvars.sizeA <= handles.options.max_size_thr) & ...
(handles.ROIvars.fitness <= handles.options.min_fitness) & ...
(handles.ROIvars.fitness_delta <= handles.options.min_fitness_delta);
handles.A_keep = handles.A(:,handles.keep); 
%the values  for what the User choose to define as discarded and accepted component (not computed)
handles.disc = zeros(size(handles.keep));
handles.accp = zeros(size(handles.keep));
%first plottings
axes(handles.template_fig);
colormap gray
[handles.CC,~,im] = plot_contours(handles.A_keep,handles.template,handles.options,0,[],[],[],find(handles.keep));
set(im,'ButtonDownFcn',@(hObject,eventdata)ROI_GUI('template_fig_ButtonDownFcn',hObject,eventdata,guidata(hObject)));
%the image funtion will not fire until hit test is turned on
set(im,'HitTest','on');
axes(handles.traceplot);
plot(handles.ROIvars.C(1,:));
guidata(hObject, handles);
uiwait()
```

**Comment by epnev** [comment]
@pgoltstein @HagaiHargil Sorry for the delayed response, we've been putting most of our effort in the Python package lately https://github.com/simonsfoundation/caiman  where we implemented our new online algorithm.

I'll try to integrate your suggestions, but you can also create a pull request if you think you have identified a bug.

@jkobject Thanks for the comment. Stupid question from me: How do you close the GUI? Just closing the window produces an error and does not save the GUIout variable.

**Comment by HagaiHargil** [comment]
Hi @epnev and thank you for your reply.

Unfortunately for me and @pgoltstein, my fixes didn't solve this issue for all datasets. I'm trying to narrow it down ATM, and I'll be happy to submit the pull request once I understand what's going on. 

I just saw your OnACID publication and it looks great. Would you recommend moving away from the MATLAB implementation considering this, and perhaps future, publications? Do you expect the Pythonic version to receive more updates and support? The CaImAn README still claims that a couple of features aren't implemented yet, but I'm not sure if the README itself is updated, and whether these features are crucial.

Best.

**Comment by HagaiHargil** [comment]
Hi again,

On the first run on some `.tif` stack I receive the following error: 
```matlab
Error using determine_search_location (line 67)
Input to EIG must not contain NaN or Inf.

Error in update_spatial_components (line 81)
        IND = determine_search_location(A_(:,1:K),method,options);

Error in run_CNMF_patches (line 262)
    [A,b,C,Pm] = update_spatial_components(data,C,fin,[A,bin],Pm,options);

Error in run_pipeline (line 127)
[A,b,C,f,S,P,RESULTS,YrA] = run_CNMF_patches(data,K,patches,tau,p,options);
```

However, once I re-run only the section containing the `run_CNMF_patches` function it runs smoothly. I guess it's some variable that isn't instantiated properly. 

Then I'm able to run the rest of the `pipeline`, and the GUI opens, with some functions working better than others. The save button works, outputting a nice `.json` with data for each cell (location and fluorescence values). I can also click inside a cell and press "Bad", which results in the GUI discarding it. 

On the negative side, I encountered a few bugs:
1. After pressing "save" - every action I try to make with the GUI results in MATLAB prompting me to save the `json` yet again. 
2. The time-trace in the lower part of the screen always shows the same trace. 
3. The `REFINE` button apparently deletes all ROIs.
4. The variable assignment seems to be wrong:
```matlab
    GUIout = ROI_GUI(Y,A,P,options,Cn,C,b,f);   
    A =GUIout{1}; 
    options = GUIout{2};
    Cdec = GUIout{3};
    ROIvars = GUIout{4};
    YrA=GUIout{5};
    Contours=GUIout{6};
    b=GUIout{7};
    f=GUIout{8};
```
For example - `GUIout{5}` seems to be the contour coordinates, not `6`. `ROIvars` is definitely not number 4, and so on.

If you could help me out with this `eig` function I might be able to send a proper pull request :)
Hagai.

**Comment by jkobject** [comment]
Hi, 

It is true that this GUI is not entirely finished ATM, as I show in the TODO.txt file, some options are not finished yet, 
Your first example is one of them. The output is for the moment not tested and certainly contains errors. This part still requires some analysis. 

For the refine deleting ROIs, I don't really understand why. But still something seemed odd when I look. I don't think the `else` statement should be present and the `if` statement should end there in the `refine_Callback` function. Else it is just redoing the original pipeline if new components have been found and continuing it by doing a merge operation and a further refining. 

In addition, I had problems with the ranking function which seems not to receive the right vector of good and discarded components. 

The last problem which is maybe related is the inability to perform a great deconvolution. There is a new problem there that I did not have before. 

For the moment as stated in the TODO list, the GUI is not flexible and require a certain amount of parameters in a certain way and to end with the deconvolution done ( else it displays an error message saying that it cannot output the deconvolved traces ). 

It is hard for me to have a thorough look to debug these problems with a challenging timetable in the next weeks. But as soon as I have some time back, I will. 

Best,

**Comment by epnev** [comment]
@HagaiHargil If you are familiar with python I would recommend to at least try it out. We have more resources dedicated to python and in the future we plan to promote python more. There is no GUI there either, but that might also come at some point. I'll take a look at the error you get and see if I can figure it out.

**Comment by HagaiHargil** [comment]
Thank you, I will try it out. Like most of us, I prefer Python any day of the week :)

One comment I would like to point out - one of the unmentioned issues we have with the new MATLAB GUI is that it changes your script's output. The updated traces are saved in a `.json` file - which is clear and easy to parse - but is also very different from what we had up to this point. Since we obviously post-process the extracted traces following your pipeline, adapting our own pipeline to this new output requires some work.

It can be reassuring for us to know that as few changes as possible will be made to the "official" pipeline's output. 

Thanks again for your hard work and dedication, we appreciate it.

**Comment by epnev** [comment]
I'm removing the GUI from the pipeline for the time being. Will introduce again once (and if) a friendlier version becomes available. The code has been changed to include several new features and performance is significantly better compared to recent past
